# Generated by Django 5.0.2 on 2024-06-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_alter_sudokupuzzle_solved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
